name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell environment
      uses: actions/setup-powershell@v2
      with:
        pwsh-version: '7.1' 

    - name: Execute PowerShell script
      shell: pwsh
      run: |
        .\env.ps1
        Write-Output "Environment variables loaded."

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan --var-file="workflow.tfvars" --var-file"policy.tfvars"
