name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        NEW_RELIC_ACCOUNT_ID: ${{ secrets.ACCOUNTID }}
        NEW_RELIC_API_KEY: ${{ secrets.APIKEY }}
      run: |
        echo "TF_VAR_accountID=${NEW_RELIC_ACCOUNT_ID}" >> $GITHUB_ENV
        echo "TF_VAR_apikey=${NEW_RELIC_API_KEY}" >> $GITHUB_ENV


    - name: Print Environment Variables
      run: printenv | grep TF_VAR_


    - name: Terraform Apply
      env:
        NEW_RELIC_ACCOUNT_ID: ${{ secrets.ACCOUNTID }}
        NEW_RELIC_API_KEY: ${{ secrets.APIKEY }}
      run: terraform apply --auto-approve --var-file="workflow.tfvars" --var-file="policy.tfvars"
