name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    - name: Terraform Init
      run: terraform init

      
    - name: Execute PowerShell script
      shell: pwsh
      run: ./env.ps1

    - name: Terraform Plan
      run: terraform plan --var-file="workflow.tfvars" --var-file="policy.tfvars"

    - name: Terraform apply
      run: terraform apply --auto-approve --var-file="workflow.tfvars" --var-file"policy.tfvars"
