name: Destroy Terraform Resources

on:
  push:  

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   env:
      apikey: ${{ secrets.apikey }}
      accountID: ${{secrets.accountID}}
   steps:
   - name: Terraform destroy 
     run: terraform plan -var="accountID=$accountID" -var="apikey=$apikey" --var-file="workflow.tfvars" --var-file="policy.tfvars"
