name: Destroy Terraform Resources

on:
  push:  

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform destroy 
      run: terraform destroy --auto-approve --var-file="workflow.tfvars" --var-file="policy.tfvars"
